## 作業:
今天學到不同統計量之間特性，  
試著分析男生女生身高資料，  
試著回答下面的問題:  
Q1:試著用今天所教的內容，如何描述這兩組資料的樣態?    
Q2: 請問男生和女生在平均身高上誰比較高?   
Q3:請問第二題的答案和日常生活中觀察的一致嗎? 如果不一致，你覺得原因可能為何?    
上述問題透過  python 語法進行運算，
並將上述答案填寫在 (google 表單)[https://forms.gle/EDdU2Zfq8zLvDea18]
![](作業資料圖檔.PNG)

In [1]:
# library
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
import math
import statistics
import seaborn as sns

In [13]:
## 輸入資料

#你的程式碼
boy=np.array([[164,175,183,173],[176,159,165,165],[169,151,156,163],
             [169,144,170,177],[165,160,164,171]])
girl=np.array([[169,170,162,154],[183,173,169,167],[170,185,162,175],
      [168,151,181,170],[182,156,159,160]])
print("boy=",boy)
print('girl=',girl)

boy= [[164 175 183 173]
 [176 159 165 165]
 [169 151 156 163]
 [169 144 170 177]
 [165 160 164 171]]
girl= [[169 170 162 154]
 [183 173 169 167]
 [170 185 162 175]
 [168 151 181 170]
 [182 156 159 160]]


In [16]:
#Q1:試著用今天所教的內容，如何描述這兩組資料的樣態?
#暗示:  分別計算男生和女生的統計量

#你的答案
print(np.median(boy),np.median(girl))

165.0 169.0


In [17]:
#Q2: 請問男生和女生在平均身高上誰比較高? 

#你的答案
if np.median(boy)<np.median(girl):
    print('girls are taller in average')
else:        print('boys are taller in average')


girls are taller in average


In [19]:
#Q3:請問第二題的答案和日常生活中觀察的一致嗎? 如果不一致，你覺得原因可能為何? 

#你的答案
print('不一致，性別資料相反或人造資料抑或時空差距過大')

不一致，性別資料相反或人造資料抑或時空差距過大
